config/routes.rb
KickStarter::Application.routes.draw do

  root :to => 'projects#index'

  resources :projects do
    collection do
      get :top_hits
    end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :abstract, :budget, :description, :title

  def self.expensive
    self.where('budget > ?', 100)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :find_project, :only => [:edit, :update, :destroy]

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(params[:project])
    if @project.save
      redirect_to projects_path
    else
      redirect_to :back
    end
  end

  def index
    @projects = Project.all
  end

  def edit
    # @project = Project.find params[:id]
  end

  def update
    # @project = Project.find params[:id]
    @project.update_attributes(params[:project])
    redirect_to projects_path
  end

  def destroy
    # @project = Project.find params[:id]
    @project.destroy
    redirect_to projects_path
  end

  def show
    @project = Project.find params[:id]
  end

  def top_hits
    @projects = Project.expensive
  end

  private
    def find_project
      @project = Project.find params[:id]
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KickStarter</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project do |f|%>
  <%= f.label :title %>
  </br>
  <%= f.text_field :title%>
  </br>
  <%= f.label :description %>
  </br>
  <%= f.text_field :description%>
  </br>
  <%= f.label :abstract %>
  </br>
  <%= f.text_field :abstract%>
  </br>
  <%= f.label :budget %>
  </br>
  <%= f.text_field :budget%>
  </br>
  <%= f.submit button_name%>
<%end%>

app/views/projects/edit.html.erb
<%= render 'form', button_name: 'Update'%>

</br>
</br>
<%= link_to 'Back', projects_path%>

app/views/projects/index.html.erb
<%= stylesheet_link_tag 'project'%>
<h2 id= 'main_content'> This is index page </h2>
<h3> Project Listing </h3>
<%= link_to 'Add Project', new_project_path%>
</br>
</br>
<% @projects.each do |project|%>
  <%= project.title %>
  <%= project.abstract%>
  <%= link_to 'View Details', project_path(project.id)%>
  <%= link_to 'Edit', edit_project_path(project.id)%>
  <%= link_to 'Delete', project_path(project.id), method: 'delete'%>
  </br>
  </br>
<%end%>

</br>
</br>
</br>
<%= link_to 'View Top Projects', top_hits_projects_path%>

app/views/projects/new.html.erb
<h1>Hello... This is new page</h1>
<h2> Add New Project </h2>
<%= render 'form', button_name: 'Add'%>

app/views/projects/show.html.erb
<h2>Title: <%= @project.title%></h2>
<h2>Description: <%= @project.description%></h2>
<h2>Abstract: <%= @project.abstract%></h2>
<h2>Budget: $ <%= @project.budget%></h2>

app/views/projects/top_hits.html.erb
<% @projects.each do |project|%>
  <%= project.title %>
  <%= project.abstract%>
  <%= project.description%>
  <%= project.budget%>
  </br>
  </br>
<%end%>